import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const src = fs.readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8');
const hook = src.slice(src.indexOf('function useMemoKeyboard()'), src.indexOf('let floatingLayer'));
const events = {};
const context = { useRef: value => ({current:value}), useEffect: f => f(), window: {addEventListener:(k,f)=>events[k]=f,removeEventListener(){}}, requestAnimationFrame:f=>f() };
vm.createContext(context);
vm.runInContext(hook+'\nthis.keyboard = useMemoKeyboard();',context);
let submitted=0, text='', cursor;
const el = {value:'가나다',selectionStart:3,selectionEnd:3,setSelectionRange:(a,b)=>cursor=[a,b]};
const event = (key, extra={}) => ({key,code:key===' '?'Space':key,nativeEvent:{isComposing:false},currentTarget:el,preventDefault(){},...extra});
const send = ()=>submitted++;
const setText = v=>text=v;
context.keyboard.onKeyDown(event('Enter'),send,setText);
assert.equal(submitted,1);
context.keyboard.onKeyDown(event('Enter',{nativeEvent:{isComposing:true}}),send,setText);
assert.equal(submitted,1,'IME confirmation must not submit');
context.keyboard.onKeyDown(event(' '),send,setText);
el.value+=' ';el.selectionStart=4;el.selectionEnd=4;
context.keyboard.onKeyDown(event('Enter'),send,setText);
assert.equal(text,'가나다\n');assert.equal(submitted,1);assert.deepEqual(cursor,[4,4]);
context.keyboard.onKeyUp(event(' '));
context.keyboard.onKeyDown(event('Enter'),send,setText);assert.equal(submitted,2);
context.keyboard.onKeyDown(event(' '),send,setText);events.blur();
context.keyboard.onKeyDown(event('Enter'),send,setText);assert.equal(submitted,3,'blur resets held space');
context.keyboard.onKeyDown(event('Enter',{repeat:true}),send,setText);assert.equal(submitted,3);
console.log('✓ Enter submission, Space+Enter newline, IME, key release, focus loss, repeat guards');
